name: Update.theme

on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
  schedule:
    - cron: 0 */1 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Set git
      run : |
        git config --global user.email "194788255+Jaykwok2999@users.noreply.github.com"
        git config --global user.name "Jaykwok2999"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0  
        
    - name: Update
      run: |

        rm -rf ./*
        
        
         
        git clone https://github.com/sbwml/luci-theme-argon.git ./tmp
        mv ./tmp/* ./
        rm -rf ./tmp
        rm -rf luci-theme-argon/htdocs/luci-static/argon/icon
        cp -af .github/argon/icon luci-theme-argon/htdocs/luci-static/argon/
        rm -rf luci-theme-argon/htdocs/luci-static/argon/img
        cp -af .github/argon/img luci-theme-argon/htdocs/luci-static/argon/
        rm -rf luci-theme-argon/htdocs/luci-static/argon/favicon.ico
        cp -af .github/argon/favicon.ico luci-theme-argon/htdocs/luci-static/argon/
        
        
        
        
    - name: Apply
      run: |
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        for pkg in $(git diff-tree --no-commit-id --name-only HEAD); do
          if [ "$(grep "PKG_RELEASE" $pkg/Makefile)" ]; then
            sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=$(git rev-list --count main $pkg)/" $pkg/Makefile || true
          fi
        done
        git reset --soft HEAD^
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d" "%H:%M:%S)"
        git push -f
